=== Pavelronaldo/xml_parser/target/classes/Medications.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
>

    <xs:simpleType name="groupRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ANTIBIOTICS"/>
            <xs:enumeration value="PAIN_RELIEVERS"/>
            <xs:enumeration value="VITAMINS"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="versionRestriction">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TABLETS"/>
            <xs:enumeration value="CAPSULES"/>
            <xs:enumeration value="POWDER"/>
            <xs:enumeration value="DROPS"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="countRestriction">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>

        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priceRestriction">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="0.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="medicines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="medicine" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>

                            <xs:element name="group">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="groupRestriction"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="pharm" type="xs:string"/>

                            <xs:element name="certificate">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id" type="xs:int"/>
                                        <xs:element name="organization" type="xs:string"/>
                                        <xs:element name="date" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="package">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="price">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="priceRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>

                                        <xs:element name="packageType" type="xs:string"/>


                                        <xs:element name="count">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="countRestriction"/>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="version">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="versionRestriction"/>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Pavelronaldo/xml_parser/src/main/resources/Medications.xml
<?xml version="1.0" encoding="UTF-8"?>
<medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="Medications.xsd">
    <medicine id="1">
        <name>Eclipse</name>
        <group>ANTIBIOTICS</group>
        <pharm>Ukraine</pharm>
        <certificate>
            <id>1234234</id>
            <organization>GrayCom</organization>
            <date>2001-12-12</date>
        </certificate>
        <package>
            <price>10.0</price>
            <packageType>type1</packageType>
            <count>10</count>
        </package>
        <version>CAPSULES</version>
    </medicine>

    <medicine id="2">
        <name>VITAMIN-D</name>
        <group>VITAMINS</group>
        <pharm>UkraineCom</pharm>
        <certificate>
            <id>29304</id>
            <organization>ChatyGome</organization>
            <date>2010-11-12</date>
        </certificate>
        <package>
            <price>30.0</price>
            <packageType>type2</packageType>
            <count>20</count>
        </package>
        <version>DROPS</version>
    </medicine>

    <medicine id="3">
        <name>LamportBakery</name>
        <group>PAIN_RELIEVERS</group>
        <pharm>Ukraine</pharm>
        <certificate>
            <id>905932</id>
            <organization>OperatingSystem</organization>
            <date>2020-11-11</date>
        </certificate>
        <package>
            <price>1.0</price>
            <packageType>package1</packageType>
            <count>1</count>
        </package>
        <version>TABLETS</version>
    </medicine>
</medicines>
